In [1]:
import torch

In [3]:
x = torch.arange(16)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
x.reshape(-1,8)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [15]:
torch.ones(2,3,4)
torch.ones((2,3,4))
print(torch.ones([2,3,4]))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [24]:
torch.randn(3, 4)
torch.normal(mean=3,std=1,size=(3,4))

tensor([[ 1.3570, -0.7851,  0.7696, -0.9807],
        [ 0.4684, -1.3230, -0.5737,  0.7296],
        [-0.2742, -1.2124, -0.0735, -0.2326]])

In [20]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [27]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [31]:
x = torch.arange(12).reshape((3,4));print(x)
y = torch.arange(-1,-13,-1).reshape(3,4);print(y)
torch.cat((x,y), dim=0), torch.cat((x,y), dim=1)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ -1,  -2,  -3,  -4],
        [ -5,  -6,  -7,  -8],
        [ -9, -10, -11, -12]])


(tensor([[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]),
 tensor([[  0,   1,   2,   3,  -1,  -2,  -3,  -4],
         [  4,   5,   6,   7,  -5,  -6,  -7,  -8],
         [  8,   9,  10,  11,  -9, -10, -11, -12]]))

In [34]:
x==y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [43]:
x.sum().dtype

torch.int64

In [49]:
a = torch.arange(0, 3).reshape(1, 3)
b = torch.arange(0, 2).reshape(2, 1)
a,b,a+b

(tensor([[0, 1, 2]]),
 tensor([[0],
         [1]]),
 tensor([[0, 1, 2],
         [1, 2, 3]]))

In [55]:
x = torch.arange(12).reshape(3, 4)
x,x[-1],x[1:3],x[1,2],x[1:3,2],x[:,2]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor(6),
 tensor([ 6, 10]),
 tensor([ 2,  6, 10]))

In [62]:
# 节省内存
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(X)
X += Y # 或者 X[:] = X + Y
id(X) == before

True

In [65]:
X > Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [58]:
X = [1,23, 2, 4]
Y = [5, 6, 7, 8]
before = id(X)
X += Y
id(X) == before

True

In [59]:
X = [1,23, 2, 4]
Y = [5, 6, 7, 8]
before = id(X)
X = X + Y
id(X) == before

False

In [67]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [70]:
a = torch.tensor([3.6])
a, a.item(), float(a), int(a)

(tensor([3.6000]), 3.5999999046325684, 3.5999999046325684, 3)