In [1]:
import torch
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
B.add_(1)
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.],
         [17., 18., 19., 20.]]))

In [2]:
A*B # 对应元素操作

tensor([[  0.,   2.,   6.,  12.],
        [ 20.,  30.,  42.,  56.],
        [ 72.,  90., 110., 132.],
        [156., 182., 210., 240.],
        [272., 306., 342., 380.]])

In [3]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X,(a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [11]:
# 降维
x = torch.randn(3, 4)
x, x.sum(dim=0), x.sum(dim=1), x.sum()



(tensor([[ 0.2506, -0.6598,  1.4358, -0.0087],
         [ 0.2227,  0.7952, -0.3177,  0.0060],
         [ 0.3050, -1.0844, -0.7748,  0.0449]]),
 tensor([ 0.7784, -0.9489,  0.3433,  0.0422]),
 tensor([ 1.0179,  0.7063, -1.5092]),
 tensor(0.2150))

In [12]:
x, x.sum(axis=0), x.sum(axis=1) # axis和dim参数相同效果，指定求和维度

(tensor([[ 0.2506, -0.6598,  1.4358, -0.0087],
         [ 0.2227,  0.7952, -0.3177,  0.0060],
         [ 0.3050, -1.0844, -0.7748,  0.0449]]),
 tensor([ 0.7784, -0.9489,  0.3433,  0.0422]),
 tensor([ 1.0179,  0.7063, -1.5092]))

In [13]:
sum_A = A.sum(dim=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [14]:
sum_A = A.sum(dim=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [16]:
#如果我们想沿某个轴计算A元素的累积总和， 
#比如axis=0（按行计算），可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。
A, A.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [28]:
# 点积
x = torch.arange(5,dtype=torch.float32)
y = torch.ones(5,dtype=torch.float32)
x,y, torch.dot(x,y) # 必须类型一致

(tensor([0., 1., 2., 3., 4.]), tensor([1., 1., 1., 1., 1.]), tensor(10.))

In [30]:
x = torch.arange(5)
y = torch.ones(5)
torch.sum(x * y) # x*y 不需要类型一致

tensor(10.)

In [44]:
# 矩阵向量积
A = torch.arange(20).reshape(5,4)
x = torch.arange(4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14,  38,  62,  86, 110]))

In [47]:
A/A.sum(axis=0)

tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

In [46]:
A/A.sum(axis=1,keepdim=True) # 第二个维度就必须保留维度才能广播

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [40]:
B = torch.ones((4, 3),dtype=int)
torch.mm(A, B)

tensor([[ 6,  6,  6],
        [22, 22, 22],
        [38, 38, 38],
        [54, 54, 54],
        [70, 70, 70]])

In [41]:
X = torch.arange(24).reshape(2,3,4)
len(X)

2