In [1]:
import torch
import torch.nn as nn


In [6]:
class Reduction(nn.Module):
    def __init__(self, in_dim, out_dim) -> None:
        super().__init__()

        self.weight = nn.Parameter(torch.randn(in_dim, in_dim, out_dim))

    def forward(self,x):

        x_outer = torch.einsum('bi,bj->bij', x, x)
        x_weighted = torch.einsum('bij,jkl->bil', x_outer, self.weight)
        return x_weighted.sum(dim=1)

batch_size = 1
in_dim = 3
out_dim = 2

model = Reduction(in_dim, out_dim)

x = torch.randn(batch_size, in_dim)
output = model.forward(x)

print("Input:")
print(x)
print("\nOutput:")
print(output)

Input:
tensor([[0.0121, 0.8635, 0.5801]])

Output:
tensor([[-2.2759,  1.0463]], grad_fn=<SumBackward1>)


In [7]:
import torch.fft as fft

class FourierLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, X):
        X = fft.fft(X) #对输入X进行快速傅里叶变换
        X = X[:,:,:X.shape[2]//2] # 取出前半部分
        return X

X = torch.rand(1, 2, 5)
net = FourierLayer()
net(X)

tensor([[[ 1.4397+0.0000j, -0.1286+0.2895j],
         [ 1.6399+0.0000j, -1.0664+0.4352j]]])